// Solution Architect Portfolio — Tailwind Brand Theme
// Generated by systematic-dev-kit:brand-designer
//
// Usage: import in tailwind.config.js
//   const brandTheme = require('./brand/tailwind.brand.js');
//   module.exports = { theme: { extend: brandTheme } }

module.exports = {
  colors: {
    primary: {
      50: 'hsl(224 38% 97%)',
      100: 'hsl(224 36% 90%)',
      200: 'hsl(224 38% 78%)',
      300: 'hsl(224 40% 63%)',
      400: 'hsl(224 42% 46%)',
      500: 'hsl(224 43% 33%)',
      600: 'hsl(224 43% 20%)',
      DEFAULT: 'hsl(var(--color-primary-h) var(--color-primary-s) var(--color-primary-l))',
      700: 'hsl(224 48% 16%)',
      800: 'hsl(224 52% 12%)',
      900: 'hsl(224 56% 8%)',
    },
    secondary: {
      50: 'hsl(40 54% 96%)',
      100: 'hsl(40 50% 88%)',
      200: 'hsl(40 52% 76%)',
      300: 'hsl(40 54% 63%)',
      400: 'hsl(40 54% 56%)',
      500: 'hsl(40 54% 50%)',
      DEFAULT: 'hsl(var(--color-secondary-h) var(--color-secondary-s) var(--color-secondary-l))',
      600: 'hsl(40 58% 42%)',
      700: 'hsl(40 62% 33%)',
      800: 'hsl(40 65% 25%)',
      900: 'hsl(40 68% 17%)',
    },
    accent: {
      50: 'hsl(27 50% 96%)',
      100: 'hsl(27 48% 88%)',
      200: 'hsl(27 50% 76%)',
      300: 'hsl(27 52% 64%)',
      400: 'hsl(27 54% 55%)',
      500: 'hsl(27 56% 46%)',
      DEFAULT: 'hsl(var(--color-accent-h) var(--color-accent-s) var(--color-accent-l))',
      600: 'hsl(27 60% 38%)',
      700: 'hsl(27 64% 30%)',
      800: 'hsl(27 66% 22%)',
      900: 'hsl(27 68% 15%)',
    },
    domain: {
      frontend: 'var(--color-domain-frontend)',
      backend: 'var(--color-domain-backend)',
      data: 'var(--color-domain-data)',
      infra: 'var(--color-domain-infra)',
    },
    bg: 'var(--color-bg)',
    surface: 'var(--color-surface)',
    border: 'var(--color-border)',
    text: {
      DEFAULT: 'var(--color-text)',
      secondary: 'var(--color-text-secondary)',
      muted: 'var(--color-text-muted)',
    },
    success: 'var(--color-success)',
    warning: 'var(--color-warning)',
    error: 'var(--color-error)',
    info: 'var(--color-info)',
  },
  fontFamily: {
    heading: ['var(--font-heading)'],
    body: ['var(--font-body)'],
    mono: ['var(--font-mono)'],
  },
  fontSize: {
    display: ['var(--text-display)', { lineHeight: 'var(--leading-tight)', letterSpacing: '-0.03em' }],
    h1: ['var(--text-h1)', { lineHeight: 'var(--leading-tight)', letterSpacing: '-0.02em' }],
    h2: ['var(--text-h2)', { lineHeight: 'var(--leading-tight)', letterSpacing: '-0.01em' }],
    h3: ['var(--text-h3)', { lineHeight: 'var(--leading-snug)', letterSpacing: '0' }],
    h4: ['var(--text-h4)', { lineHeight: 'var(--leading-snug)', letterSpacing: '0' }],
    'body-lg': ['var(--text-body-lg)', { lineHeight: 'var(--leading-relaxed)' }],
    body: ['var(--text-body)', { lineHeight: 'var(--leading-normal)' }],
    'body-sm': ['var(--text-body-sm)', { lineHeight: 'var(--leading-normal)' }],
    caption: ['var(--text-caption)', { lineHeight: 'var(--leading-normal)' }],
  },
  spacing: {
    xs: 'var(--space-xs)',
    sm: 'var(--space-sm)',
    md: 'var(--space-md)',
    lg: 'var(--space-lg)',
    xl: 'var(--space-xl)',
    '2xl': 'var(--space-2xl)',
    '3xl': 'var(--space-3xl)',
  },
  borderRadius: {
    sm: 'var(--radius-sm)',
    md: 'var(--radius-md)',
    lg: 'var(--radius-lg)',
    full: 'var(--radius-full)',
  },
  boxShadow: {
    sm: 'var(--shadow-sm)',
    md: 'var(--shadow-md)',
    lg: 'var(--shadow-lg)',
  },
  transitionDuration: {
    fast: '150ms',
    normal: '280ms',
    slow: '420ms',
  },
  transitionTimingFunction: {
    brand: 'cubic-bezier(0.25, 0.05, 0.25, 1)',
  },
};
