// Solution Architect Portfolio — Tailwind Brand Theme
// Generated by systematic-dev-kit:brand-designer
//
// Stellar cartography identity — dark-only brand.
// All color tokens reference CSS custom properties defined in brand-theme.css.
//
// Usage: import in tailwind.config.js
//   const brandTheme = require('./brand/tailwind.brand.js');
//   module.exports = { theme: { extend: brandTheme } }

module.exports = {
  colors: {
    primary: {
      50:  'hsl(238 35% 97%)',
      100: 'hsl(238 36% 92%)',
      200: 'hsl(238 36% 82%)',
      300: 'hsl(238 37% 68%)',
      400: 'hsl(238 37% 52%)',
      500: 'hsl(238 37% 38%)',
      600: 'hsl(238 37% 28%)',
      700: 'hsl(238 37% 22%)',
      800: 'hsl(238 37% 16%)',
      900: 'hsl(238 40% 10%)',
      DEFAULT: 'hsl(var(--color-primary-h) var(--color-primary-s) var(--color-primary-l))',
    },
    secondary: {
      50:  'hsl(38 60% 97%)',
      100: 'hsl(38 60% 90%)',
      200: 'hsl(38 62% 78%)',
      300: 'hsl(38 62% 65%)',
      400: 'hsl(38 63% 56%)',
      500: 'hsl(38 63% 47%)',
      600: 'hsl(38 65% 38%)',
      700: 'hsl(38 66% 30%)',
      800: 'hsl(38 68% 22%)',
      900: 'hsl(38 70% 14%)',
      DEFAULT: 'hsl(var(--color-secondary-h) var(--color-secondary-s) var(--color-secondary-l))',
    },
    accent: {
      DEFAULT: 'hsl(var(--color-accent-h) var(--color-accent-s) var(--color-accent-l))',
    },
    domain: {
      frontend: 'var(--color-domain-frontend)',
      backend:  'var(--color-domain-backend)',
      data:     'var(--color-domain-data)',
      infra:    'var(--color-domain-infra)',
    },
    bg:      'var(--color-bg)',
    surface: 'var(--color-surface)',
    border:  'var(--color-border)',
    text: {
      DEFAULT:   'var(--color-text)',
      secondary: 'var(--color-text-secondary)',
      muted:     'var(--color-text-muted)',
    },
    success: 'var(--color-success)',
    warning: 'var(--color-warning)',
    error:   'var(--color-error)',
    info:    'var(--color-info)',
  },
  fontFamily: {
    heading: ['var(--font-heading)'],
    body:    ['var(--font-body)'],
    mono:    ['var(--font-mono)'],
  },
  fontSize: {
    display:   ['var(--text-display)',  { lineHeight: 'var(--leading-tight)',   letterSpacing: '-0.03em' }],
    h1:        ['var(--text-h1)',        { lineHeight: 'var(--leading-tight)',   letterSpacing: '-0.02em' }],
    h2:        ['var(--text-h2)',        { lineHeight: 'var(--leading-snug)',    letterSpacing: '-0.02em' }],
    h3:        ['var(--text-h3)',        { lineHeight: 'var(--leading-snug)',    letterSpacing: '-0.01em' }],
    h4:        ['var(--text-h4)',        { lineHeight: 'var(--leading-snug)',    letterSpacing: '0' }],
    'body-lg': ['var(--text-body-lg)',   { lineHeight: 'var(--leading-relaxed)' }],
    body:      ['var(--text-body)',      { lineHeight: 'var(--leading-normal)'  }],
    'body-sm': ['var(--text-body-sm)',   { lineHeight: 'var(--leading-normal)'  }],
    caption:   ['var(--text-caption)',   { lineHeight: 'var(--leading-normal)',  letterSpacing: '0.06em' }],
  },
  spacing: {
    xs:   'var(--space-xs)',
    sm:   'var(--space-sm)',
    md:   'var(--space-md)',
    lg:   'var(--space-lg)',
    xl:   'var(--space-xl)',
    '2xl': 'var(--space-2xl)',
    '3xl': 'var(--space-3xl)',
  },
  borderRadius: {
    sm:   'var(--radius-sm)',
    md:   'var(--radius-md)',
    lg:   'var(--radius-lg)',
    full: 'var(--radius-full)',
  },
  boxShadow: {
    sm: 'var(--shadow-sm)',
    md: 'var(--shadow-md)',
    lg: 'var(--shadow-lg)',
  },
  transitionDuration: {
    fast:   '120ms',
    normal: '300ms',
    slow:   '500ms',
  },
  transitionTimingFunction: {
    brand: 'cubic-bezier(0.16, 1, 0.3, 1)',
  },
};
